# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(783da6b0-4600-4264-bef4-72b5a03afe51)'
    subscriptionId: '783da6b0-4600-4264-bef4-72b5a03afe51'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dev'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/zeleandro/minesweeper/main/CreateWepApp/azuredeploy.json'
    overrideParameters: '-projectName Minesweeper'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- script: |
  displayName: 'Run a multi-line script'
